# Site settings
title: Parcela
version: 0.0.1
email: marco@parcela.io
description: ""
baseurl: ""
url: "http://parcela.github.io"
twitter_username: ParcelaLib
github_username:  Parcela

# Build settings
highlighter: rouge
markdown: redcarpet
permalink: pretty

redcarpet:
  input: GFM
  extensions: [with_toc_data, prettify, hard_wrap]


# Defaults per scope
